/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { HttpResponse, http } from "msw";
import { faker } from "@faker-js/faker";

faker.seed(1);

const baseURL = "http://localhost:4000/v1";

export const handlers = [
  http.get(`${baseURL}/stats`, async () => {
    const resultArray = [
      [getGetStats200Response(), { status: 200 }],
      [getGetStats401Response(), { status: 401 }],
      [getGetStats403Response(), { status: 403 }],
      [getGetStats500Response(), { status: 500 }],
    ];

    return HttpResponse.json(
      ...resultArray[3],
    );
  }),
];

export function getGetStats200Response() {
  return [
    { questionnaires: { rating: 8007946480680889 } },
    { questionnaires: { rating: 5012051888907662 } },
  ];
}

export function getGetStats401Response() {
  return null;
}

export function getGetStats403Response() {
  return null;
}

export function getGetStats500Response() {
  return null;
}
