// This file is auto-generated by @hey-api/openapi-ts

export const $User = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        }
    }
} as const;

export const $UserInput = {
    type: 'object',
    required: ['name', 'email'],
    properties: {
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        }
    }
} as const;

export const $Post = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        title: {
            type: 'string'
        },
        content: {
            type: 'string'
        },
        userId: {
            type: 'integer'
        }
    }
} as const;

export const $PostInput = {
    type: 'object',
    required: ['title', 'content', 'userId'],
    properties: {
        title: {
            type: 'string'
        },
        content: {
            type: 'string'
        },
        userId: {
            type: 'integer'
        }
    }
} as const;