// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import type { ApiResult } from './core/ApiResult';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class DefaultService {
    /**
     * Get all users
     * @returns unknown A list of users
     * @throws ApiError
     */
    public static getUsers(): CancelablePromise<ApiResult<$OpenApiTs['/users']['get']['res'][200]>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/users'
        });
    }
    
    /**
     * Create a new user
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown User created
     * @throws ApiError
     */
    public static postUsers(data: $OpenApiTs['/users']['post']['req']): CancelablePromise<ApiResult<$OpenApiTs['/users']['post']['res'][201]>> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/users',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Get a user by ID
     * @param data The data for the request.
     * @param data.id
     * @returns unknown A user
     * @throws ApiError
     */
    public static getUsersById(data: $OpenApiTs['/users/{id}']['get']['req']): CancelablePromise<ApiResult<$OpenApiTs['/users/{id}']['get']['res'][200]>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/users/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * Update a user
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns unknown User updated
     * @throws ApiError
     */
    public static putUsersById(data: $OpenApiTs['/users/{id}']['put']['req']): CancelablePromise<ApiResult<$OpenApiTs['/users/{id}']['put']['res'][200]>> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/users/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Delete a user
     * @param data The data for the request.
     * @param data.id
     * @returns void User deleted
     * @throws ApiError
     */
    public static deleteUsersById(data: $OpenApiTs['/users/{id}']['delete']['req']): CancelablePromise<ApiResult<$OpenApiTs['/users/{id}']['delete']['res'][204]>> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/users/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * Get all posts
     * @returns unknown A list of posts
     * @throws ApiError
     */
    public static getPosts(): CancelablePromise<ApiResult<$OpenApiTs['/posts']['get']['res'][200]>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/posts'
        });
    }
    
    /**
     * Create a new post
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Post created
     * @throws ApiError
     */
    public static postPosts(data: $OpenApiTs['/posts']['post']['req']): CancelablePromise<ApiResult<$OpenApiTs['/posts']['post']['res'][201]>> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/posts',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Get a post by ID
     * @param data The data for the request.
     * @param data.id
     * @returns unknown A post
     * @throws ApiError
     */
    public static getPostsById(data: $OpenApiTs['/posts/{id}']['get']['req']): CancelablePromise<ApiResult<$OpenApiTs['/posts/{id}']['get']['res'][200]>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/posts/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * Update a post
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns unknown Post updated
     * @throws ApiError
     */
    public static putPostsById(data: $OpenApiTs['/posts/{id}']['put']['req']): CancelablePromise<ApiResult<$OpenApiTs['/posts/{id}']['put']['res'][200]>> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/posts/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Delete a post
     * @param data The data for the request.
     * @param data.id
     * @returns void Post deleted
     * @throws ApiError
     */
    public static deletePostsById(data: $OpenApiTs['/posts/{id}']['delete']['req']): CancelablePromise<ApiResult<$OpenApiTs['/posts/{id}']['delete']['res'][204]>> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/posts/{id}',
            path: {
                id: data.id
            }
        });
    }
    
}