// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import type { ApiResult } from './core/ApiResult';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class StatsService {
    /**
     * Get a list of scripts
     * @returns Stats Statistics for Dashboard page
     * @throws ApiError
     */
    public static getStats(): CancelablePromise<ApiResult<$OpenApiTs['/stats']['get']['res'][200]>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/stats',
            errors: {
                401: `Invalid or no authorisation provided.
`,
                403: `Insufficient access.
`,
                500: `The server encountered an unexpected condition that prevented it from fulfilling the request.
`
            }
        });
    }
    
}