// This file is auto-generated by @hey-api/openapi-ts

export type User = {
    id?: number;
    name?: string;
    email?: string;
};

export type UserInput = {
    name: string;
    email: string;
};

export type Post = {
    id?: number;
    title?: string;
    content?: string;
    userId?: number;
};

export type PostInput = {
    title: string;
    content: string;
    userId: number;
};

export type UserId = number;

export type PostId = number;

export type $OpenApiTs = {
    '/users': {
        get: {
            res: {
                /**
                 * A list of users
                 */
                200: unknown;
            };
        };
        post: {
            req: {
                requestBody: UserInput;
            };
            res: {
                /**
                 * User created
                 */
                201: unknown;
            };
        };
    };
    '/users/{id}': {
        get: {
            req: {
                id: number;
            };
            res: {
                /**
                 * A user
                 */
                200: unknown;
            };
        };
        put: {
            req: {
                id: number;
                requestBody: UserInput;
            };
            res: {
                /**
                 * User updated
                 */
                200: unknown;
            };
        };
        delete: {
            req: {
                id: number;
            };
            res: {
                /**
                 * User deleted
                 */
                204: void;
            };
        };
    };
    '/posts': {
        get: {
            res: {
                /**
                 * A list of posts
                 */
                200: unknown;
            };
        };
        post: {
            req: {
                requestBody: PostInput;
            };
            res: {
                /**
                 * Post created
                 */
                201: unknown;
            };
        };
    };
    '/posts/{id}': {
        get: {
            req: {
                id: number;
            };
            res: {
                /**
                 * A post
                 */
                200: unknown;
            };
        };
        put: {
            req: {
                id: number;
                requestBody: PostInput;
            };
            res: {
                /**
                 * Post updated
                 */
                200: unknown;
            };
        };
        delete: {
            req: {
                id: number;
            };
            res: {
                /**
                 * Post deleted
                 */
                204: void;
            };
        };
    };
};